CppLibraries = {
    iostream
    string
    sstream
    concepts
    type_traits
    list
    vector
    iterator
    stdexcept
    ostream
    memory
    unordered_map
    sstream
    vector
    any
    cmath
}