Commands = {
    { def ; def [0] [1]([args]): ; [0] [1](args) ; 1 }
    { def ; def [0]([args]): ; void [0](args) ; 1 }
    { print ; print([0]) ; std::cout<<[0]; ; 0 }
    { print ; print([0], [1]) ; std::cout<<[0]<<[1]; ; 0 }
}