Commands = {
    { def @ def [0] [1]([args]): @ [0] [1](args) @ 3 }
    { def @ def [0]([args]): @ void [0](args) @ 3 }
    { print @ print([0]) @ std::cout<<[0]<<'\n'; @ 2 }
    { print @ print([0], [1]) @ std::cout<<[0]<<[1]; @ 2 }
}
TypeBinders = {
    { Var<int64_t> @ int64 }
    { Var<int32_t> @ int }
    { Var<int8_t> @ int8 }
    { Var<uint64_t> @ uint64 }
    { Var<uint32_t> @ uint }
    { Var<uint8_t> @ uint8 }
    { Var<double> @ fl2 }
    { Var<float> @ fl1 }
    { Var<std::string> @ str }
    { bool @ bool }
}
