TypeBinders = {
    { Array<int64_t> @ list<int64> }
    { Array<std::string> @ list<str> }
    { Array<double> @ list<fl2> }
    { Array<int64_t> @ Array<int64> }
    { Matr<int64_t> @ Matr<int64> }
    { Array<double> @ Array<fl2> }
    { Matr<double> @ Matr<fl2> }
    { Array<float> @ Array<fl1> }
    { Matr<float> @ Matr<fl1> }
    { Array<std::string> @ Array<str> }
    { Matr<std::string> @ Matr<str> }
    { Var<int64_t> @ int64 }
    { Var<int32_t> @ int }
    { Var<int8_t> @ int8 }
    { Var<uint64_t> @ uint64 }
    { Var<uint32_t> @ uint }
    { Var<uint8_t> @ uint8 }
    { Var<double> @ fl2 }
    { Var<float> @ fl1 }
    { Var<std::string> @ str }
    { Var<bool> @ bool }
}
